version: '3.9'

services:
  site1:
    build:
      context: ./site1
      dockerfile: ../Dockerfile
    ports:
      - "8081:80"

  site2:
    build:
      context: ./site2
      dockerfile: ../Dockerfile
    ports:
      - "8082:80"

  site3:
    build:
      context: ./site3
      dockerfile: ../Dockerfile
    ports:
      - "8083:80"

  site4:
    build:
      context: ./site4
      dockerfile: ../Dockerfile
    ports:
      - "8084:80"

  site5:
    build:
      context: ./site5
      dockerfile: ../Dockerfile
    ports:
      - "8085:80"
  site6:
    build:
      context: ./site1
      dockerfile: ../Dockerfile
    ports:
      - "8086:80"
  site7:
    build:
      context: ./site1
      dockerfile: ../Dockerfile
    ports:
      - "8087:80"
  site8:
    build:
      context: ./site1
      dockerfile: ../Dockerfile
    ports:
      - "8088:80"

  site9:
    build:
      context: ./site1
      dockerfile: ../Dockerfile
    ports:
      - "8089:80"


  site10:
    build:
      context: ./site1
      dockerfile: ../Dockerfile
    ports:
      - "8090:80"

